// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IUniswapV2Router01$Type } from "./IUniswapV2Router01";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IUniswapV2Router01"]: IUniswapV2Router01$Type;
    ["@uniswap/v2-periphery/contracts/interfaces/IUniswapV2Router01.sol:IUniswapV2Router01"]: IUniswapV2Router01$Type;
  }
}
