// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { EddyFinanceAddLiquidity$Type } from "./EddyFinanceAddLiquidity";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EddyFinanceAddLiquidity"]: EddyFinanceAddLiquidity$Type;
    ["contracts/EddyAddLiquidity.sol:EddyFinanceAddLiquidity"]: EddyFinanceAddLiquidity$Type;
  }
}
