// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IUniswapV2Router02$Type } from "./IUniswapV2Router02";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IUniswapV2Router02"]: IUniswapV2Router02$Type;
    ["@uniswap/v2-periphery/contracts/interfaces/IUniswapV2Router02.sol:IUniswapV2Router02"]: IUniswapV2Router02$Type;
  }
}
