// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IUniswapV2Factory$Type } from "./IUniswapV2Factory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IUniswapV2Factory"]: IUniswapV2Factory$Type;
    ["@uniswap/v2-core/contracts/interfaces/IUniswapV2Factory.sol:IUniswapV2Factory"]: IUniswapV2Factory$Type;
  }
}
